### ISSUE TITLE
License/Etiquette question

### ISSUE THREAD

**Issue by qwertystop** [billzorn/mtgencode#9]
I'm forking this to adapt to the Pokemon TCG - I think the card structure there is different enough to potentially have some quite interesting results. I'm not quite sure how the etiquette and licensing works for this situation, though - do I rename my fork now or only once I've actually made the changes? How do I write the license to account for the fact that the structure of the code is yours but many details will be mine? That sort of thing. I would prefer to defer to @billzorn in this situation, as the initial maker of the code.

**Comment by billzorn** [comment]
This code is under the MIT license, so essentially you can do whatever you want with it as long as you also make your work based on it available under the same license. For the fine print, refer to the LICENSE file.

I would say, go ahead and rename your fork as soon as possible just so that your work is easier to distinguish from mine. You'll probably want to restructure the readme and so on, depending on how you change the code, but maybe leave a little note and a link back to the original code to let people know what your project is based on. Of course if it's a fork there will also be github's automatic indicators.

I'm less concerned with getting credit for my work, and more concerned with making sure that future users of the codebase will have a clear understanding of what's going on. If this work is useful to you, then that's awesome! I'm glad I could help.

**Comment by qwertystop** [comment]
Gotcha, thanks.
